services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tariki_db
      POSTGRES_USER: tariki
      POSTGRES_PASSWORD: tariki
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tariki_db
      SPRING_DATASOURCE_USERNAME: tariki
      SPRING_DATASOURCE_PASSWORD: tariki
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tariki.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  db_data:
  pgadmin_data:
